/**
 * This is a TwoFold 2✂f module that provides
 * tags for my Cr;Lf; personal blog.
 */

import fs from "node:fs";
import path from "node:path";
import { homedir } from "node:os";

import { marked } from "marked";
import { minify } from "html-minifier-next";
import markedLinkifyIt from "marked-linkify-it";

// TwoFold dependencies
import Runtime from "./twofold/src/runtime.ts";
import { TemplateEngine } from "./twofold/src/tmpl.ts";
import { DiskCache } from "./twofold/src/cache.ts";
import { getText } from "./twofold/src/tags.ts";

type Params = Record<string, any>;

const diskCache = new DiskCache("cache");
const TTL = 1000 * 60 * 60 * 24; // 1 day
const HOME_DIR = homedir();

const CACHE_BLOGS = Object.values(
  JSON.parse(fs.readFileSync("cache/blogs.json", "utf8")),
);
const MEM_TITLES = JSON.parse(fs.readFileSync("cache/mem_info.json", "utf8"));

marked.use({ breaks: true, gfm: true }, markedLinkifyIt());

// Extend the TypeScript global interfaces
declare global {
  interface String {
    toTitleCase(): string;
  }
  interface Date {
    format(fmtText: string): string;
  }
}
//
// Extend the runtime String prototype
String.prototype.toTitleCase = function titleCase(): string {
  return this.replace(
    /\w\S*/g,
    (text) => text.charAt(0).toUpperCase() + text.substring(1).toLowerCase(),
  );
};
//
// Extend the runtime Date prototype
Date.prototype.format = function formatDate(fmtText: string): string {
  const utcDate = new Date(this.toUTCString());
  const year = utcDate.getUTCFullYear();
  const month = utcDate.getUTCMonth();
  const day = utcDate.getUTCDate();
  const weekday = utcDate.getUTCDay();
  const monthsShort = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const daysShort = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

  // Helper to pad numbers
  const pad = (num: number, size: number): string =>
    String(num).padStart(size, "0");

  // Format mapping
  const formatMap = {
    yyyy: year,
    yy: String(year).slice(-2),
    LLL: monthsShort[month],
    LL: pad(month + 1, 2),
    L: month + 1,
    dd: pad(day, 2),
    d: day,
    ccc: daysShort[weekday],
  };

  // Replace format tokens
  let result = fmtText;
  for (const [token, value] of Object.entries(formatMap)) {
    result = result.replace(token, value);
  }

  return result;
};

export function markdown(_t: string, args: Params): string {
  /*
   * 2✂︎f tag that renders markdown to HTML.
   */
  let src = args.src || args.file || args.path;
  if (!src) {
    console.warn("No source file provided for the Markdown tag.");
    return "";
  }
  if (src[0] === "~") {
    src = src.replace(/^~(?=$|\/|\\)/, HOME_DIR);
  }
  const text = fs.readFileSync(src, "utf-8");
  return "\n" + marked.parse(text).trim() + "\n";
}

async function minified(html: string): Promise<string> {
  const min = await minify(html, {
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    preserveLineBreaks: true,
    removeComments: true,
    keepClosingSlash: false,
    useShortDoctype: true,
    minifyCSS: true,
  });
  return min;
}

export function partial(_t: string, args: Params, meta: Runtime): string {
  /*
   * 2✂︎f tag that includes another snippet file
   * and renders it with the current context.
   */
  let src = args.src || args.file || args.path;
  if (!src) {
    console.warn("No source file provided for the Partial tag.");
    return "";
  }
  const text = fs.readFileSync(src, "utf-8");
  // Inject page variables
  // const shortFn = path.basename(meta.file.fname!).toLowerCase().split(".")[0];
  return "\n" + new TemplateEngine().render(text, { ...args }).trim() + "\n";
}

export function title(text: string, _a: Params, meta: Runtime): undefined {
  /*
   * 2✂︎f tag that caches the title of the page.
   */
  if (!text) {
    console.warn("No text provided for the title tag.");
    return;
  }
  if (!meta.file.fname?.endsWith(".md")) {
    // console.warn("Title tag can only be used in MD files.");
    return;
  }
  const shortFn = path.basename(meta.file.fname!).toLowerCase().split(".")[0];
  console.log("Adding title text:", shortFn, "=", text);
  const memInfo: Params = diskCache.getCache("mem_info", shortFn) || {
    title: text,
  };
  diskCache.setCache("mem_info", shortFn, memInfo, TTL);
  // HACK
  meta.globalCtx.title = text;
}

export function link(text: string, _a: Params, meta: Runtime): any {
  /*
   * 2✂︎f tag that defines links between memos in MEM.
   * The link doesn't return anything, just caches the relationship.
   * This could also show up in regular HTML, so be careful!
   *
   * Example:
   * {link id=whatever} [Whatever](./whatever) {/link}
   */
  const params = meta.node.params || {};
  if (!meta.file.fname?.endsWith(".md")) {
    // console.warn("Link tag can only be used in MD files.");
    return;
  }
  if (!params.id) {
    const m = text.match(/\(\.\/(.+?)\)/);
    if (m && m[1]) {
      params.id = m[1];
    } else {
      // console.warn("No link provided in text or ID! Skipping link.");
      return;
    }
  }

  const id = params.id.toLowerCase();
  const shortFn = path.basename(meta.file.fname!).toLowerCase().split(".")[0];
  console.log("Adding link:", shortFn, "->", id);

  let dirLinks = new Set<string>();
  try {
    dirLinks = new Set<string>(diskCache.getCache("dir_links", shortFn) || []);
  } catch (err: any) {
    console.error("Error reading dir_links cache:", err.message);
  }
  let bckLinks = new Set<string>();
  try {
    bckLinks = new Set<string>(diskCache.getCache("bck_links", id) || []);
  } catch (err: any) {
    console.error("Error reading bck_links cache:", err.message);
  }

  dirLinks.add(id);
  bckLinks.add(shortFn);
  diskCache.setCache("dir_links", shortFn, Array.from(dirLinks), TTL);
  diskCache.setCache("bck_links", id, Array.from(bckLinks), TTL);

  if (MEM_TITLES[id]?.value?.title) {
    return `[${MEM_TITLES[id].value.title}](./${id})`;
  }
}

export function backlinks(_t: string, args: Params, meta: Runtime): string {
  /*
   * 2✂︎f tag that populates back-references between memos.
   * Example:
   * {backlinks}
   *   [Something1](./something1)
   *   [Something2](./something2)
   * {/backlinks}
   */
  let to = args.to;
  if (!to) {
    let fname = meta.file.fname!.toLowerCase();
    fname = fname.split("/").pop() || fname;
    to = fname.split(".")[0]; // Remove extension
  }
  const bckLinks = (diskCache.getCache("bck_links", to) || [])
    .sort((a, b) => a.localeCompare(b))
    .map((id: string) => {
      const linkText = MEM_TITLES[id]?.value?.title || id.toTitleCase();
      return `[${linkText}](./${id})`;
    });
  console.log("Backlinks for:", to, "=>", bckLinks);
  if (bckLinks.length === 0) {
    return "";
  }
  return "Backlinks: " + bckLinks.join(", ") + ".\n";
}

function isArticle(entry: Params): boolean {
  // Helper function for blogs.
  // By convention, first tag is the most important
  // so the first tag=article becomes the category
  return entry.tags.indexOf("article") > -1 || entry.text.length > 10_000;
}

function getReadingTime(text: string): number {
  // Helper function for blogs.
  const wordsPerMinute = 200;
  const numberOfWords = text.split(/\s/g).length;
  return Math.ceil(numberOfWords / wordsPerMinute);
}

function escapeText(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

async function _renderTemplate(
  args: Params,
  meta: Runtime,
): Promise<string | undefined> {
  let src = args.in || args.tmpl;
  if (!src) {
    console.warn("args 'in' or 'tmpl' parameter is required! Skipping!");
    return;
  }
  if (src[0] === "~") {
    src = src.replace(/^~(?=$|\/|\\)/, HOME_DIR);
  }

  let text = new TemplateEngine().renderFile(src, args);
  const engine = Runtime.fromText(
    text,
    meta.customTags,
    meta.config,
    meta.memoCache,
  );
  text = await engine.evaluateAll({ ...args });
  text = new TemplateEngine().render(text, args);

  // Fix and replace stuff
  text = text.replaceAll(/<partial src=".+?">/g, "");
  text = text.replaceAll(/<\/partial>/g, "");
  // External links should open in a new tab
  text = text.replaceAll(
    /(<a href="https?:.+?")>/g,
    '$1 rel="noopener" target="_blank">',
  );

  const min = await minified(text);
  return min;
}

export async function plainRender(
  _t: string,
  args: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to render a plain HTML page.
   */
  if (!args.out) {
    console.warn("args 'out' parameter is required! Skipping!");
    return;
  }
  const min = await _renderTemplate(args, meta);
  if (!min) return;
  console.log("Writing plain render:", args.out);
  fs.mkdirSync(`output/${path.dirname(args.out)}`, { recursive: true });
  fs.writeFileSync(`output/${args.out}`, min, "utf-8");
}

export async function blog(
  _t: string,
  _a: Params,
  meta: Runtime,
): Promise<undefined> {
  // The text content is in the children nodes
  const text = meta.node
    .children!.filter((n) => n.rawText && n.rawText.trim() !== "")
    .map((n) => n.rawText)
    .join("")
    .trim();
  if (!text) return;

  // @ts-ignore It's grand!
  let ctx = meta.node.childCtx;
  if (!ctx.date || !ctx.title) return;
  const key = `${ctx.date.slice(2).replaceAll("-", "")}-${ctx.link || "1"}`;

  const blog: Params = {};
  blog.date = ctx.date;
  blog.id = path.basename(meta.file.fname!).toLowerCase().split(".")[0];
  blog.layout = "post";
  blog.tags = ctx.tags || [];
  blog.title = ctx.title;
  blog.topic = isArticle({ ...ctx, text }) ? "articles" : "notes";
  blog.url = `/log/entries/${key}/`;
  if (ctx.draft) {
    console.log("Blog is a draft:", blog.url);
    blog.draft = true;
  }
  blog.isoDate = new Date(ctx.date)
    .toISOString()
    .replace("T", " ")
    .replace(/\.000Z$/, "");
  blog.readingTime = getReadingTime(text);
  // Cache into BLOGS!
  diskCache.setCache("blogs", key, blog, TTL);

  ctx.tmpl = `tmpl/${blog.layout}.html`;
  ctx.content = marked.parse(text);
  const min = await _renderTemplate({ ...ctx, ...blog }, meta);
  if (!min) return;

  fs.mkdirSync(`output/${blog.url}`, { recursive: true });
  console.log("Writing blog:", blog.url, "Title:", blog.title);
  fs.writeFileSync(`output/${blog.url}/index.html`, min, "utf-8");
}

export async function memo(
  _t: string,
  _a: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to generate a single MEMO page.
   */
  const nodes = meta.node.children!.filter((n) => n.name !== "title");
  const text = getText({ children: nodes }).trim();
  if (!text) return;

  const id = path.basename(meta.file.fname!).toLowerCase().split(".")[0];
  // @ts-ignore It's grand!
  const ctx = meta.node.childCtx;
  ctx.content = marked.parse(text);
  ctx.title = ctx.title || id.toTitleCase();
  ctx.tmpl = "tmpl/wiki.html";
  ctx.layout = "wiki";
  ctx.id = id;

  let html = await _renderTemplate(ctx, meta);
  if (!html) return;
  // Fix and replace stuff
  html = html.replace(/<p>(.+?)<br>In:/, "In:");
  // Relative links should point to MEM
  html = html.replaceAll(/<a href="\.\/(.+?)">/g, '<a href="/mem/$1">');
  html = html.replaceAll(
    /<img src="\.\/img\/(.+?)"/g,
    '<img src="/mem/img/$1"',
  );

  fs.mkdirSync(`output/mem/${id}`, { recursive: true });
  if (id === "index") {
    console.log("Writing index memo page.");
    fs.writeFileSync(`output/mem/index.html`, html, "utf-8");
  } else {
    fs.writeFileSync(`output/mem/${id}/index.html`, html, "utf-8");
  }
}

export async function photo(
  _t: string,
  args: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to define and generate a photo page.
   */
  if (!args.date || !args.title) {
    console.warn("Photo tag requires date and title! Skipping!");
    return;
  }
  if (!(args.image || args.images)) {
    console.warn("Photo tag requires image or images parameters! Skipping!");
    return;
  }

  const key = `${args.date.slice(2).replaceAll("-", "")}-${
    args.title.replaceAll(
      " ",
      "-",
    )
  }`.toLowerCase();
  const url = `/log/photos/${key}/`;

  const blog: Params = CACHE_BLOGS.map((e: any) => e.value)
    .filter((e: Params) => e.topic === "photos" && e.url == url)
    .at(0) || {};
  blog.date = args.date;
  blog.id = key;
  blog.layout = "post";
  blog.title = escapeText(args.title);
  blog.topic = "photos";
  blog.url = url;
  if (args.text) {
    blog.text = escapeText(args.text);
    if (!blog.text.endsWith(".")) {
      blog.text += ".";
    }
  }
  blog.isoDate = new Date(args.date)
    .toISOString()
    .replace("T", " ")
    .replace(/\.000Z$/, "");
  if (args.image) blog.image = args.image;
  if (args.images && Array.isArray(args.images)) blog.images = args.images;
  // Cache into BLOGS!
  diskCache.setCache("blogs", key, blog, TTL);

  args.tmpl = `tmpl/${blog.layout}.html`;
  args.content = blog.text ? `\n<p>${blog.text}</p>\n` : "";
  args.content += args.images
    ? args.images
      .map(
        (img: string) =>
          `<p><img src="/log/img/photos/${img}" alt="${args.text}" title="${args.title}"></p>`,
      )
      .join("\n")
    : `<p><img src="/log/img/photos/${args.image}" alt="${blog.text}" title="${blog.title}"></p>`;

  const min = await _renderTemplate({ ...args, ...blog }, meta);
  if (!min) return;

  fs.mkdirSync(`output/${url}`, { recursive: true });
  console.log("Writing photo:", url, "Title:", blog.title);
  fs.writeFileSync(`output/${url}/index.html`, min, "utf-8");
}

export async function img(
  _t: string,
  args: Params,
  _m: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to enable img-DB generated image tags.
   */
  if (
    !args["data-pth"] ||
    !args["data-format"] ||
    !args["data-mode"] ||
    !args.src
  ) {
    return;
  }

  const pth = args["data-pth"].split("/").at(-1);
  const info = CACHE_BLOGS.map((e: any) => e.value)
    .filter(
      (e: Params) =>
        e.topic === "photos" &&
        (e.image === pth || (e.images && e.images.includes(pth))),
    )
    .at(0);
  for (const k of Object.keys(args)) {
    if (k.startsWith("data-") && k.endsWith("hash")) info[k] = args[k];
  }
  if (args["data-top-colors"]) {
    info["data-top-colors"] = args["data-top-colors"];
  }
  info.src = args.src;
  // Cache into BLOGS!
  diskCache.setCache("blogs", info.id, info, TTL);

  console.log("Cached img-DB info for:", pth);
}

export function tags(_t: string, _a: Params, _m: Runtime): string {
  /**
   * 2✂︎f tag used to generate the full list of tags.
   */
  const blogs = CACHE_BLOGS.map((e: any) => e.value);
  const unsortedTags: Record<string, number> = {};
  let tags = "";
  blogs.forEach((p: Params) => {
    if (!p.tags) return;
    for (const t of p.tags) {
      if (
        !t ||
        t === "article" ||
        t === "articles" ||
        t === "entries" ||
        t === "entry" ||
        t === "note" ||
        t === "notes"
      ) {
        continue;
      }
      if (!unsortedTags[t]) {
        unsortedTags[t] = 1;
      } else {
        unsortedTags[t] += 1;
      }
    }
  });
  for (
    const t of Object.keys(unsortedTags).sort(
      (a, b) => unsortedTags[b] - unsortedTags[a],
    )
  ) {
    tags += `  <postList id=tag tag="${t}" count=${unsortedTags[t]}/>\n`;
  }
  console.log(`Generated ${Object.keys(unsortedTags).length} tags list.`);
  return "\n  " + tags.trim() + "\n";
}

export async function postList(
  _t: string,
  args: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to generate a listing of blog posts.
   */
  const ctx: Params = { id: args.id, blog: args.blog, theme: args.theme };
  ctx.layout = args.tmpl ? args.tmpl : "list";
  ctx.title = args.title || args.id.toTitleCase();
  ctx.tmpl = args.tmpl ? `tmpl/${args.tmpl}.html` : "tmpl/list.html";
  ctx.url = ("/" + (args.id === "index" ? "" : args.id) + "/").replaceAll(
    "//",
    "/",
  );
  if (args.id === "articles" || args.id === "notes" || args.id === "photos") {
    ctx.ico = args.blog.topics[args.id];
  } else if (args.id === "tag") {
    ctx.title = `Tagged '${args.tag}'`;
    ctx.url = `/tags/${args.tag}/`;
  }
  ctx.posts = CACHE_BLOGS.map((e: any) => e.value).sort((a: any, b: any) =>
    a.date < b.date ? 1 : -1
  );

  if (args.id === "index") {
    ctx.posts = ctx.posts
      .filter(
        (p: Params) =>
          !p.draft && (p.topic === "articles" || p.topic === "notes"),
      )
      .slice(0, 6);
  } else if (
    args.id === "articles" ||
    args.id === "notes" ||
    args.id === "photos"
  ) {
    ctx.posts = ctx.posts.filter(
      (p: Params) => !p.draft && p.topic === args.id,
    );
  } else if (args.id === "drafts") {
    ctx.posts = ctx.posts.filter((p: Params) => p.draft);
  } else if (args.id === "tag" && args.tag) {
    // individual tag page
    ctx.posts = ctx.posts.filter(
      (p: Params) => !p.draft && p.tags && p.tags.includes(args.tag),
    );
  }

  if (args.tmpl === "topic") {
    const unsortedTags: Record<string, number> = {};
    const sorted: Record<string, number> = {};
    ctx.posts.forEach((p: Params) => {
      if (!p.tags) return;
      for (const t of p.tags) {
        if (
          t === "entries" ||
          t === "article" ||
          t === "articles" ||
          t === "note" ||
          t === "notes"
        ) {
          continue;
        }
        if (!unsortedTags[t]) {
          unsortedTags[t] = 1;
        } else {
          unsortedTags[t] += 1;
        }
      }
    });
    for (
      const t of Object.keys(unsortedTags).sort(
        (a, b) => unsortedTags[b] - unsortedTags[a],
      )
    ) {
      sorted[t] = unsortedTags[t];
    }
    ctx.tags = sorted;
  }

  const min = await _renderTemplate(ctx, meta);
  if (!min) return;
  console.log("Writing listing:", ctx.url, "with", ctx.posts.length, "entries");
  fs.mkdirSync(`output/${ctx.url}/`, { recursive: true });
  fs.writeFileSync(`output/${ctx.url}/index.html`, min, "utf-8");
}

export async function feedXml(
  _t: string,
  _a: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to generate an Atom feed XML.
   */
  const engine = await Runtime.fromFile(
    "tmpl/feed.xml",
    meta.customTags,
    meta.config,
    meta.memoCache,
  );

  const blog: Record<string, any> = Bun.TOML.parse(
    fs.readFileSync("data/blog.toml", "utf-8"),
  );
  const blogs = CACHE_BLOGS.map((e: any) => {
    e.value.absoluteUrl = `${blog.url}${e.value.url}`;
    return e.value;
  }).sort((a: any, b: any) => (a.date < b.date ? 1 : -1));
  const ctx = { blog, recent: blogs.slice(0, 8) };

  const tmpl = await engine.evaluateAll(ctx);
  const xml = new TemplateEngine().render(tmpl, ctx);
  fs.writeFileSync("output/feed.xml", xml, "utf-8");
}

export async function siteXml(
  _t: string,
  _a: Params,
  meta: Runtime,
): Promise<undefined> {
  /**
   * 2✂︎f tag used to generate an Atom feed XML.
   */
  const engine = await Runtime.fromFile(
    "tmpl/sitemap.xml",
    meta.customTags,
    meta.config,
    meta.memoCache,
  );

  const blog: Record<string, any> = Bun.TOML.parse(
    fs.readFileSync("data/blog.toml", "utf-8"),
  );
  const pages = CACHE_BLOGS.map((e: any) => {
    e.value.absoluteUrl = `${blog.url}${e.value.url}`;
    return e.value;
  }).sort((a: any, b: any) => (a.date < b.date ? 1 : -1));
  const date = new Date().toISOString().split("T")[0];
  pages.push({ date, absoluteUrl: `${blog.url}/articles/` });
  pages.push({ date, absoluteUrl: `${blog.url}/notes/` });
  pages.push({ date, absoluteUrl: `${blog.url}/photos/` });
  pages.push({ date, absoluteUrl: `${blog.url}/topics/` });
  pages.push({ date, absoluteUrl: `${blog.url}/about/` });
  pages.push({ date, absoluteUrl: `${blog.url}/author/` });
  pages.push({ date, absoluteUrl: `${blog.url}/projects/` });
  const ctx = { blog, pages };

  const tmpl = await engine.evaluateAll(ctx);
  const xml = new TemplateEngine().render(tmpl, ctx);
  fs.writeFileSync("output/sitemap.xml", xml, "utf-8");
}
